version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y zip
      - if [ -f lambda/requirements.txt ]; then pip install -r lambda/requirements.txt -t lambda/; fi
  build:
    commands:
      - echo Packaging Lambda function...
      - cd lambda
      - zip -r ../lambda.zip .
      - cd ..
  post_build:
    commands:
      - echo Build completed.
artifacts:
  files:
    - lambda.zip
    - cloudformation/**/*
  discard-paths: yes
